apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-std
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 3400Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-prem

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 3400Gi
